### ISSUE TITLE
How to invert and edit an image

### ISSUE THREAD

**Issue by ramtiin** [orpatashnik/StyleCLIP#1]
Hello,

I looked at the codes but couldn't locate the code that inverts the image so it can be edited. You said you used e4e, but I couldn't find the relevant codes.

Thank you.

**Comment by orpatashnik** [comment]
Hi @ramtiin ,

Thanks for your interest in the project! The code of e4e will be released within the next few days [here](https://github.com/omertov/encoder4editing).
In the meanwhile, I recommend performing the inversion using [pSp](https://github.com/eladrich/pixel2style2pixel). The pSp repository contains a notebook that is really easy to work with. Let me know if you need any help.

**Comment by ramtiin** [comment]
Thank you for your fast response!

I opened [this notebook](https://github.com/eladrich/pixel2style2pixel/blob/master/notebooks/inference_playground.ipynb) and set experiment_type to ffhq_encode, but I couldn't figure out how to get a latent code. I can only get the inversion in png format. Do you know which part I need to change?

**Comment by woctezuma** [comment]
You could use the official implementation:

https://github.com/NVlabs/stylegan2-ada-pytorch#projecting-images-to-latent-space

**Comment by orpatashnik** [comment]
As @woctezuma mentioned, it is also possible to invert using the official StyleGAN implementation. An advantage of using pSp is the fast inference. To obtain the latent code from pSp's notebook, you can modify it as follows:

![image](https://user-images.githubusercontent.com/24733041/107982544-e91dfc00-6fcc-11eb-8f7c-51bf3a721442.png)

It is important to note that different latent codes behave differently when trying to edit them, so you may need to tune a bit the `--l2_lambda` parameter. Anyway, I hope that the code of e4e will be available as soon as possible because the latent codes that it provides are suitable for high-quality editing :-)

**Comment by ramtiin** [comment]
Thank you! The problem has been solved, so I'm closing this issue.

**Comment by woctezuma** [comment]
FYI e4e has been released! [![Open In Colab][colab-badge]][colab-encoder4editing]

[colab-badge]: <https://colab.research.google.com/assets/colab-badge.svg>
[colab-encoder4editing]: <http://colab.research.google.com/github/omertov/encoder4editing/blob/main/notebooks/inference_playground.ipynb>
