### ISSUE TITLE
No such file or directory: './npy/ffhq/W.npy' when execute python GetCode.py

### ISSUE THREAD

**Issue by kennethliukai** [orpatashnik/StyleCLIP#29]
I try the code in StyleCLIP_global.ipynb, the first job is to prepare the input data. When I execute the following commends, I get the FileNotFoundError:

Traceback (most recent call last):
  File "GetCode.py", line 214, in <module>
    save_tmp=GetS(dataset_name,num_img=2_000)
  File "GetCode.py", line 132, in GetS
    dlatents=np.load(tmp)[:num_img]
  File "/Users/liukai/opt/anaconda3/lib/python3.8/site-packages/numpy/lib/npyio.py", line 416, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: './npy/ffhq/W.npy'

dataset_name='ffhq' #@param ['ffhq'] {allow-input: true}
# input dataset name 

#%cd /content/StyleCLIP/global/

# input prepare data 
!python GetCode.py --dataset_name $dataset_name --code_type 'w' 
!python GetCode.py --dataset_name $dataset_name --code_type 's' 
!python GetCode.py --dataset_name $dataset_name --code_type 's_mean_std' 

Anyone can help, thanks.

**Comment by betterze** [comment]
Dear kennethliukai,

Thank you for your interest in our work. 

I just rerun the global notbook, but failed to reproduce the error. I believe the error you show is due to another error in the following line 

```
!python GetCode.py --dataset_name $dataset_name --code_type 'w'
```

Would you mind rerun the notebook to see if you still meet the same error? If so, would you mind just running the line in above, to see if there is a error? If so, please inform us the log of error.

Best Wishes,

Alex
